# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumAdjustExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumAdjustExample
  pod 'TealiumAdjust', :path=> '../'
  pod 'tealium-swift/Collect', '~> 2.3'
  pod 'tealium-swift/Lifecycle', '~> 2.3'
  pod 'tealium-swift/Attribution', '~> 2.3'
end
